[Eth]
NetworkId = 159
SyncMode = "full"
StateHistory = 90000
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasFloor = 0
GasCeil = 30000000
GasPrice = 1000000000
Recommit = 2000000000
NewPayloadTimeout = 2000000000

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 5120
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.BlobPool]
Datadir = "blobpool"
Datacap = 10737418240
PriceBump = 100

[Eth.GPO]
Blocks = 20
Percentile = 60
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 500000000000
IgnorePrice = 2

[Node]
DataDir = "/roburna-go/data/testnet/node"
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool", "debug", "engine", "personal", "miner", "admin"]
WSHost = "0.0.0.0"
WSPort = 8545
WSModules = ["net", "web3", "eth", "personal"]
NoUSB = true
InsecureUnlockAllowed = true

[Node.P2P]
MaxPeers = 200
NoDiscovery = true
ListenAddr = ":30311"
DiscAddr = ""
EnableMsgEvents = false
StaticNodes = ["enode://2bf28dd129b8b053cca37388dea3b08f3d194646d96695c1b86f00dedbc4451a53ff85ea70db25349a3b69f69461935eaf799ba6c218026b88c50e7c1b4696f7@65.109.11.176:30311"]